name: "Header Split: <file>.h -> <file>.h/.cpp"
description: "Mechanical split with strict rules"
title: "header-split: <file>"
labels: ["header-split", "mechanical", "safe-change"]
body:
  - type: markdown
    attributes:
      value: |
        **MANDATORY RULES**
        1) Do NOT introduce new functions/variables or change signatures.
        2) No logic edits. Only move declarations to .h and definitions to .cpp.
        3) Include tightening via IWYU (no globals re-coupling).
        4) Respect aggregate-init policy (CI scanner will fail otherwise).
        5) Build must pass; behaviour must remain 1:1 on hardware.

  - type: input
    id: header
    attributes: { label: "Header to split", placeholder: "include/foo.h" }
    validations: { required: true }

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Link to any cycles/ODR findings relevant to this file."
