name: Firmware CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio regex==2024.5.15 networkx==3.3 graphviz==0.20.3

      - name: Cache PIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: pio-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}

      - name: Make runner executable
        run: chmod +x agent_runner.sh

      - name: Build (all envs)
        run: ./agent_runner.sh pio run

      - name: Dependency report (JSON + Mermaid + DOT)
        run: ./agent_runner.sh python3 tools/deps_stub_report.py src include lib

      - name: Check analysis artifacts
        run: |
          test -s analysis/deps_report.json
          test -s analysis/deps_mermaid.md
          test -s analysis/deps_graph.dot
          ls -lh analysis/

      - name: Aggregate-init scanner (STRICT)
        run: ./agent_runner.sh python3 tools/aggregate_init_scanner.py --mode=strict --roots src include lib

      - name: Generate compile_commands.json
        run: ./agent_runner.sh pio run -t compiledb

      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analysis
          path: |
            analysis/**
            compile_commands.json
