name: Firmware CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Cache PIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: pio-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}

      - name: Build (all environments)
        run: |
          pio run

      - name: Install analysis deps
        run: |
          pip install regex==2024.5.15
          pip install networkx==3.3 graphviz==0.20.3
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Aggregate-Init Scanner (Strict)
        run: |
          python tools/aggregate_init_scanner.py --mode=strict --roots src include lib

      - name: Dependency Report (dot + mermaid)
        run: |
          python tools/deps_stub_report.py --roots src include > analysis/deps_mermaid.md
          dot -V || true
        continue-on-error: true

      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analysis
          path: |
            .pio
            analysis/**
            **/build/**

