name: size-budget

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'scripts/verify_size_budget.py'
      - 'ci/size-baseline.json'
      - 'platformio.ini'
      - '.github/workflows/size-budget.yml'

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Check size budget
        run: |
          python scripts/verify_size_budget.py --baseline ci/size-baseline.json
